http:
  routers:
    calculate:
      rule: "PathPrefix(`/calculate`)"
      entryPoints:
        - web
      service: calculate-svc

  services:
    calculate-svc:
      loadBalancer:
        strategy: "leasttime"
        servers:
          - url: "http://app1:8000"
          - url: "http://app2:8000"
          - url: "http://app3:8000"
          - url: "http://app4:8000"
          - url: "http://app5:8000"

